config/routes.rb
Wpilife::Application.routes.draw do

  match '/search',  to: 'search#search'
  match '/search/:query', to: 'search#search'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :postings do
    collection do
      get 'all'
    end
  end
  resources :categories
  resources :posting_categories

  root to: 'static_pages#home'
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact' 

end

app/models/answer.rb
class Answer < Post
  attr_accessible :content
  belongs_to :question, inverse_of: :answers
  belongs_to :user, inverse_of: :answers
  
  #before_save { |answer| answer.name = answer.question.name }
  
  validates :content, presence: true, length: { minimum: 30 }
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :name
  
  validates :name, presence: true, length: { minimum: 3 }
end

app/models/classified_listing.rb
class ClassifiedListing < ActiveRecord::Base
  attr_accessible :content, :name, :title
end

app/models/party.rb
class Party < ActiveRecord::Base
  attr_accessible :date, :title
  acts_as_voteable
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :category_id, :content, :title
  belongs_to :user
end

app/models/posting.rb
class Posting < ActiveRecord::Base
  attr_accessible :content, :title, :posting_category_id
  belongs_to :user
  belongs_to :posting_category, inverse_of: :postings
  
  acts_as_indexed :fields => [:content, :title]
  
  validates :title, presence: true, length: { minimum: 10, maximum: 100 }
  validates :content, presence: true, length: { minimum: 50, maximum: 10000 }
  validates :user_id, presence: true
  
  default_scope order: 'postings.created_at DESC'
  
end

app/models/posting_category.rb
class PostingCategory < Category
  attr_accessible :description, :name
  has_many :postings, inverse_of: :posting_category
end

app/models/question.rb
class Question < Post
  attr_accessible :title, :body
  belongs_to :user, inverse_of: :questions
  has_many :answers, dependent: :destroy, inverse_of: :question
end

app/models/ride_post.rb
class RidePost < ActiveRecord::Base
  attr_accessible :body, :date, :title, :type
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password
  has_many :postings, dependent: :destroy
  has_many :questions, dependent: :destroy, inverse_of: :user
  has_many :answers, dependent: :destroy, inverse_of: :user
  
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 4 }
  validates :password_confirmation, presence: true
  
  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/models/vote.rb
class Vote < ActiveRecord::Base

  scope :for_voter, lambda { |*args| where(["voter_id = ? AND voter_type = ?", args.first.id, args.first.class.base_class.name]) }
  scope :for_voteable, lambda { |*args| where(["voteable_id = ? AND voteable_type = ?", args.first.id, args.first.class.base_class.name]) }
  scope :recent, lambda { |*args| where(["created_at > ?", (args.first || 2.weeks.ago)]) }
  scope :descending, order("created_at DESC")

  belongs_to :voteable, :polymorphic => true
  belongs_to :voter, :polymorphic => true

  attr_accessible :vote, :voter, :voteable


  # Comment out the line below to allow multiple votes per user.
  validates_uniqueness_of :voteable_id, :scope => [:voteable_type, :voter_type, :voter_id]

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@classified_listings = ClassifiedListing.all
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  def index
    @questions = Question.all
  end

  # GET /questions/1
  def show
    @question = Question.find(params[:id])
    @answers = @question.answers
    @reply = Answer.new
    @reply.question_id = @question.id
    @errors = @reply.errors
  end

  # GET /questions/new
  def new
    @question = Question.new
    @errors = @question.errors
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  def create
    @question = Question.new(params[:question])
    @question.user_id = current_user.id

    if @question.save
      redirect_to @question, notice: 'Question was successfully created.'
    else
      @errors = @question.errors
      render action: "new"
    end
  end

  # PUT /questions/1
  def update
    @question = Question.find(params[:id])

    if @question.update_attributes(params[:question])
      redirect_to @question, notice: 'Question was successfully updated.'
    else
      render action: "edit"
    end
  end

  # DELETE /questions/1
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    redirect_to questions_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "WPILife"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
  
  def remote_hostname
    require 'resolv'
    Resolv.getname(request.remote_ip)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/helpers/postings_helper.rb
module PostingsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/ride_posts_helper.rb
module RidePostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end
  
  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/questions/_form.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@question) do |f| %>
    <%= render 'shared/error_messages' %>

      <%= f.label :title %>
      <%= f.text_field :title %>
    
      <%#= f.label :category %>
      <%#= f.collection_select :category_id, Category.all, :id, :name,  {:include_blank => true} %>

      <%= f.label :content %>
      <%= f.text_area :content %>
    
      <%= f.submit "Post Question", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/questions/_question.html.erb
<li>
  <span class="content"><%= link_to question.title, question %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(question.created_at) %> ago.
  </span>
</li>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<% provide(:title, 'All questions') %>
<h1>All Questions</h1>

<ul class="questions">
  <%= render @questions %>
</ul>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<% provide(:title, 'Ask a Question') %>
<h1>Ask a Question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<% provide(:title, @question.title) %>
<div class="row">
  <div class="span10 offset1 question">
    <div class="row">
      <div class="span3">
        <div>
          <section>
            Posted by <%= @question.user.name %> <%= time_ago_in_words(@question.created_at) %> ago
          </section>
          <% if signed_in? && (current_user.admin? || current_user?(@question.user)) %>
            <section>
              <%= link_to "Edit", edit_question_path(@question), class: "btn btn-large btn-primary" %>
              <%= link_to "Delete", @question, class: "btn btn-large btn-primary", method: :delete,
                                        data: { confirm: "You sure?" } %>
            </section>
          <% end %>
        </div>
      </div>
      <div class="span7">
        <div>
          <h4><%= @question.title %></h4>
          <%= @question.content %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row answers">
  <%= render @question.answers %>
</div>
<div class="row reply">
  <div class="span10 offset1">
  <h4>Got an answer</h4>
    <% if signed_in? %>
      <%= form_for(@reply) do |f| %>
        <%= render 'shared/error_messages' %>
  
        <%= f.label :content %>
        <%= f.text_area :content, cols: 100, rows: 10 %>
        <br />
        <%= hidden_field :question, :id %>
        <%= f.submit "Post Answer", class: "btn btn-large btn-primary" %>
      <% end %>
    <% else %>
      <%= link_to "Sign in to contribute!", signin_path %> 
    <% end %>
  </div>
</div>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>